version: '3'

tasks:
  start:
    desc: Start the demo API
    dir: demo
    cmds:
      - go run .

  clear-db:
    desc: Clear the demo SQLite database
    dir: demo
    cmds:
      - rm -f appointments.db

  query-appointments:
    desc: Query all appointments
    dir: demo
    cmds:
      - sqlite3 appointments.db "SELECT * FROM appointments;"
